;; -*- lexical-binding: t -*-

(defun init-components ()
  (new-component! floor)
  (new-component! obj)
  (new-component! render :char)
  (new-component! plant :min-energy :max-energy)
  (new-component! deer)
  (new-component! autotroph)
  (new-component! herbivore)
  (new-component! carnivore)
  (new-component! hunger :current :max :rate )  
  (new-component! location :floor-size :obj-limit)
  (new-component! where :location)
  (new-component! reproduction :state :step :stages :min-size :reproduce-on)
  (new-component! pos :x :y :z)
  (new-component! size :current :max :rate)
  (new-component! inventory :hash)
  (new-component! exits :hash)
  (new-component! contains :hash)
  (new-component! stats :str :dex :con)
  (new-component! description :text))
