;; -*- lexical-binding: t -*-

(defun ces-seng-components ()
  (ces-new-component! stats :str :dex :con :weight)
  (ces-new-component! move :scaling-stats)
  (ces-new-component! eat :scaling-likes)
  (ces-new-component! pick :scaling-skills)
  (ces-new-component! player)
  (ces-new-component! where :current-location :headed :previous-location)
  (ces-new-component! location :floor-size :obj-soft-limit :move-speed)
  (ces-new-component! named :sname :rname :dname :description :pronoun :att)
  (ces-new-component! likes :hash :current-happiness)
  (ces-new-component! stats :speed :def :att :char)
  (ces-new-component! exits :hash)
  (ces-new-component! timers :hash)
  (ces-new-component! description :text)
  (ces-new-component! contains :hash))
